// <auto-generated />
using System;
using System.Configuration;

namespace CS_Week02_22017011_CatchButton.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SettingsSingleFileGenerator", "1.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting()]
        [DefaultSettingValue("0")]
        public int HighScore
        {
            get { return ((int)(this["HighScore"])); }
            set { this["HighScore"] = value; }
        }
    }
}
